version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Shortener.API/Dockerfile  # Шлях до Dockerfile для бекенду
    ports:
      - "5000:5001"  # Порт для бекенду
    environment:
      - ASPNETCORE_HTTP_PORTS=5001
    depends_on:
      ms-sql:
        condition: service_healthy


  # frontend:
  #   build:
  #     context: ./Shortener.Web # Встановлюємо правильний контекст для фронтенду
  #     dockerfile:  ./Dockerfile  # Шлях до Dockerfile для фронтенду
  #   ports:
  #     - "4200:4200"  # Порт для фронтенду
  #   depends_on:
  #     - backend  # Фронтенд залежить від бекенду
  #
  ms-sql:
    container_name: ms-sql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "5001:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password1* -Q 'SELECT 1' -C -o /dev/null || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s   
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data:
